import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';

// IMPORTS
import 'firebase_options.dart'; // Generated by FlutterFire
import 'screens/login_screen.dart';
import 'screens/admin/admin_dashboard.dart';
import 'screens/employee/employee_dashboard.dart';
import 'services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
    await NotificationService().initialize(); // <--- ADD THIS
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Employee System',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.grey[100],
      ),
      // INSTEAD OF LoginScreen, WE USE AuthCheck
      home: const AuthCheck(),
    );
  }
}

// ==========================================
// THE TRAFFIC CONTROLLER
// ==========================================
class AuthCheck extends StatelessWidget {
  const AuthCheck({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 1. If waiting for Firebase to check connection...
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }

        // 2. If User is Logged In
        if (snapshot.hasData) {
          return FutureBuilder<String?>(
            future: _getUserRole(snapshot.data!.uid),
            builder: (context, roleSnapshot) {
              if (roleSnapshot.connectionState == ConnectionState.waiting) {
                return const Scaffold(body: Center(child: CircularProgressIndicator()));
              }

              final role = roleSnapshot.data;

              if (role == 'admin') {
                return const AdminDashboard();
              } else if (role == 'employee') {
                return const EmployeeDashboard();
              } else {
                return const LoginScreen(); // Fallback if role is missing
              }
            },
          );
        }

        // 3. If User is Logged Out
        return const LoginScreen();
      },
    );
  }

  // Helper to find out if user is Admin or Employee
  Future<String?> _getUserRole(String uid) async {
    // First, try to get from local storage (It's faster)
    final prefs = await SharedPreferences.getInstance();
    String? role = prefs.getString('role');

    if (role != null) return role;

    // If not in local storage, fetch from Database
    try {
      DocumentSnapshot doc = await FirebaseFirestore.instance.collection('user').doc(uid).get();
      if (doc.exists) {
        role = doc['role'];
        // Save locally for next time
        await prefs.setString('role', role ?? 'employee'); 
        return role;
      }
    } catch (e) {
      return null;
    }
    return null;
  }
}