import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class SalaryScreen extends StatelessWidget {
  const SalaryScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;

    return Scaffold(
      backgroundColor: Colors.grey[50],
      appBar: AppBar(
        title: const Text("Latest Monthly Report"),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black87,
        elevation: 0,
      ),
      body: StreamBuilder<QuerySnapshot>(
        // QUERY: Get only the NEWEST slip for this user
        stream: FirebaseFirestore.instance
            .collection('salary_slips')
            .where('uid', isEqualTo: user?.uid)
            .orderBy('timestamp', descending: true) // Sort by date
            .limit(1) // Only get the top 1
            .snapshots(),
        builder: (context, snapshot) {
          // 1. Loading State
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }

          // 2. Error State
          if (snapshot.hasError) {
            // Note: If you see an index error here, check the Debug Console for the link!
            return Center(child: Text("Error: ${snapshot.error}"));
          }

          // 3. Empty State
          if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
            return _buildNoDataView();
          }

          // 4. Success State
          final data = snapshot.data!.docs.first.data() as Map<String, dynamic>;
          return _buildReportCard(data);
        },
      ),
    );
  }

  Widget _buildReportCard(Map<String, dynamic> data) {
    String month = data['month'] ?? "--";
    String year = data['year'] ?? "--";
    
    // Get values (Default to 0 if missing)
    int present = (data['present'] ?? 0).toInt();
    int absent = (data['absent'] ?? 0).toInt();
    int late = (data['late'] ?? 0).toInt();

    // Calculate Attendance Score (Just an example logic)
    double totalDays = (present + absent).toDouble();
    int score = totalDays > 0 ? ((present / totalDays) * 100).toInt() : 0;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        children: [
          // HEADER CARD
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [Colors.blue.shade900, Colors.blue.shade600],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(20),
              boxShadow: [
                BoxShadow(color: Colors.blue.withValues(alpha: 0.3), blurRadius: 15, offset: const Offset(0, 10))
              ]
            ),
            child: Column(
              children: [
                const Text("REPORT FOR", style: TextStyle(color: Colors.white70, letterSpacing: 1.2, fontSize: 12)),
                const SizedBox(height: 5),
                Text(
                  "$month $year",
                  style: const TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 20),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    _headerStat("Score", "$score%", Icons.verified),
                    Container(height: 30, width: 1, color: Colors.white24, margin: const EdgeInsets.symmetric(horizontal: 20)),
                    _headerStat("Status", score > 80 ? "Good" : "Average", Icons.thumb_up),
                  ],
                )
              ],
            ),
          ),

          const SizedBox(height: 25),

          // STATS GRID
          GridView.count(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            crossAxisCount: 2,
            crossAxisSpacing: 15,
            mainAxisSpacing: 15,
            childAspectRatio: 1.1,
            children: [
              _buildStatCard("Present", "$present Days", Colors.green, Icons.check_circle_outline),
              _buildStatCard("Absent", "$absent Days", Colors.red, Icons.cancel_outlined),
              _buildStatCard("Late", "$late Days", Colors.orange, Icons.watch_later_outlined),
              // You can add Overtime here if you added it to the upload
              _buildStatCard("Working Days", "${present+absent}", Colors.blue, Icons.calendar_today),
            ],
          ),

          const SizedBox(height: 30),
          const Text(
            "This report is generated by Admin.\nContact HR for discrepancies.",
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.grey, fontSize: 12),
          ),
        ],
      ),
    );
  }

  Widget _headerStat(String label, String value, IconData icon) {
    return Column(
      children: [
        Icon(icon, color: Colors.white, size: 20),
        const SizedBox(height: 4),
        Text(value, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
        Text(label, style: const TextStyle(color: Colors.white70, fontSize: 10)),
      ],
    );
  }

  Widget _buildStatCard(String title, String value, Color color, IconData icon) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [BoxShadow(color: Colors.grey.withValues(alpha: 0.05), blurRadius: 10)],
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(color: color.withValues(alpha: 0.1), shape: BoxShape.circle),
            child: Icon(icon, color: color, size: 24),
          ),
          const SizedBox(height: 12),
          Text(value, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
          Text(title, style: TextStyle(color: Colors.grey[600], fontSize: 12)),
        ],
      ),
    );
  }

  Widget _buildNoDataView() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.receipt_long, size: 80, color: Colors.grey[300]),
          const SizedBox(height: 15),
          const Text("No Reports Available", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 5),
          const Text("Your monthly report hasn't been uploaded yet.", style: TextStyle(color: Colors.grey)),
        ],
      ),
    );
  }
}